name: "build and deploys"
on: ["push","workflow_dispatch"]


env:
  AZURE_WEBAPP_NAME: aspnet-core-sample-deploy
  AZURE_WEBAPP_PACKAGE_PATH: './published'
  NETCORE_VERSION: '3.1.103'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Publish
      run: dotnet publish --no-build -c Release -o ./published
        


        